apiVersion: v2
name: kor
description: A Kubernetes Helm Chart to discover orphaned resources using kor
type: application
version: 0.1.8
appVersion: "0.4.3"
maintainers:
  - name: "yonahd"
    url: "https://github.com/yonahd/kor"
