run:
  timeout: 5m
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gci
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/yonahd/kor)
    custom-order: true
