project_name: kor

builds:
  - id: linux
    binary: kor
    main: ./main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/yonahd/kor/pkg/utils.Version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  - id: darwin
    binary: kor
    main: ./main.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/yonahd/kor/pkg/utils.Version={{.Version}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

  - id: windows
    binary: kor
    main: ./main.go
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -buildmode=exe
      - -X github.com/yonahd/kor/pkg/utils.Version={{.Version}}
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
changelog:
  use: github-native
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'README'
      - Merge pull request
      - Merge branch
snapshot:
  name_template: "{{ .Version }}"