project_name: kor

builds:
  - id: linux-amd64
    binary: kor
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

  - id: darwin-amd64
    binary: kor
    main: ./main.go
    goos:
      - darwin
    goarch:
      - amd64

  - id: windows-amd64
    binary: kor
    main: ./main.go
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -buildmode=exe

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'README'
      - Merge pull request
      - Merge branch
