{
 "title": "Kor Dashboard",
 "description": "A Dashboard to view unused resources in Kubernetes",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kubernetes_orphaned_resources,exported_namespace)"
    }
   },
   {
    "name": "kind",
    "query": {
     "query": "label_values(kubernetes_orphaned_resources,kind)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Unused Resources Sum (Namespace)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(exported_namespace) (kubernetes_orphaned_resources{kind=~\"$kind\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unused Resources Bar (Kind)",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kubernetes_orphaned_resources{exported_namespace=~\"$namespace\", kind=~\"$kind\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unused Resources Pie (Kind)",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubernetes_orphaned_resources{exported_namespace=~\"$namespace\", kind=~\"$kind\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unused Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unused Configmaps",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kubernetes_orphaned_resources{exported_namespace=~\"$namespace\", kind=\"ConfigMap\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Unused Secrets",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kubernetes_orphaned_resources{exported_namespace=~\"$namespace\", kind=\"Secret\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Unused Services",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kubernetes_orphaned_resources{exported_namespace=~\"$namespace\", kind=\"Service\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Unused ServiceAccounts",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kubernetes_orphaned_resources{exported_namespace=~\"$namespace\", kind=\"ServiceAccount\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Unused Deployments",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 45 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kubernetes_orphaned_resources{exported_namespace=~\"$namespace\", kind=\"Deployment\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Unused StatefulSets",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 45 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kubernetes_orphaned_resources{exported_namespace=~\"$namespace\", kind=\"StatefulSet\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Unused Roles",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 45 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kubernetes_orphaned_resources{exported_namespace=~\"$namespace\", kind=\"Role\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Unused Hpas",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 45 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kubernetes_orphaned_resources{exported_namespace=~\"$namespace\", kind=\"Hpa\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Unused Pvcs",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kubernetes_orphaned_resources{exported_namespace=~\"$namespace\", kind=\"Pvc\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Unused Ingresses",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kubernetes_orphaned_resources{exported_namespace=~\"$namespace\", kind=\"Ingress\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Unused Pdbs",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 53 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kubernetes_orphaned_resources{exported_namespace=~\"$namespace\", kind=\"Pdb\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}