name: Validate Exceptions JSON Sorting

on:
  pull_request:
    branches:
      - main
    paths:
      - "pkg/kor/exceptions/**"

jobs:
  sort_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validte Exceptions JSON Sorting
        run: make validate-exception-sorting 
